my_config_form.settings:
  type: config_object
  label: 'My config form settings'
  mapping:
    text:
      type: string
      label: The Text
    select:
      type: string
      label: The Select
    radio:
      type: string
      label: The Radio
